---
title: eventmanagement package
config:
  class:
    hideEmptyMembersBox: true
  layout: elk
  htmlLabels: false
---

classDiagram

class EventDeadlinesFragment 
class Section 
class BottomSheetProvider 
class CreateEventActivity 
class EventLotteryFragment 
class EventDateTimeFragment 
class Time 
class EventGeneralFragment 
class CreateEventModel 
class InputFragment 
class EventStyleFragment 
class DraftEventsFragment 

DraftEventsFragment --> CreateEventActivity : starts

CreateEventActivity "1" o-- "1" EventGeneralFragment : hosts
CreateEventActivity "1" o-- "1" EventDateTimeFragment : hosts
CreateEventActivity "1" o-- "1" EventDeadlinesFragment : hosts
CreateEventActivity "1" o-- "1" EventLotteryFragment : hosts
CreateEventActivity "1" o-- "1" EventStyleFragment : hosts

CreateEventActivity "1" o-- "1" CreateEventModel : watches

%% Event builder relationship
Event_Builder -- EventGeneralFragment : fills
Event_Builder -- EventDateTimeFragment : fills
Event_Builder -- EventDeadlinesFragment : fills
Event_Builder -- EventLotteryFragment : fills
Event_Builder -- EventStyleFragment : fills

%% Create Event Model Relationship
CreateEventModel "1" -- "1" EventGeneralFragment : stores input data
CreateEventModel "1" -- "1" EventDateTimeFragment : stores input data
CreateEventModel "1" -- "1" EventDeadlinesFragment : stores input data
CreateEventModel "1" -- "1" EventLotteryFragment : stores input data
CreateEventModel "1" -- "1" EventStyleFragment : stores input data

CreateEventModel "1" *-- "1" Section : stores
CreateEventModel "1" --> "1" Section : changes

note for Time "This was made because Date objects can't store time"

%% implements
BottomSheetProvider <|.. CreateEventActivity
 
InputFragment <|.. EventGeneralFragment
InputFragment <|.. EventDateTimeFragment
InputFragment <|.. EventDeadlinesFragment
InputFragment <|.. EventLotteryFragment
InputFragment <|.. EventStyleFragment


