---
title: eventmanagement package
config:
  class:
    hideEmptyMembersBox: true
  layout: elk
  htmlLabels: false
---

classDiagram
class EventDeadlinesFragment { 
- String TAG$
- ViewInputEventDeadlinesBinding binding
- CreateEventModel model
- BottomSheetProvider bottomSheetProvider
+ onCreateView(LayoutInflater,ViewGroup,Bundle) View 
+ onViewCreated(View,Bundle) void 
- setupDatePickers() void 
+ valid(InputFragment) boolean 
+ extract(Event.Builder) Event.Builder 
+ onDestroyView() void 
}

class Section { 
<<enum>>
+ Section firstSection$
+ Section lastSection$
+ GENERAL$
+ DATETIME$
+ DEADLINES$
+ LOTTERY$
+ STYLE$
+ getTitle() String 
+ isGeneralValid(String,String) boolean 
+ isDatetimeValid(Date,Time,Time) boolean 
}

class BottomSheetProvider { 
<<interface>>
~ openCalendarBottomSheet(MutableLiveData~Optional~Date~~,View) void 
~ openTimeBottomSheet(MutableLiveData~Optional~Time~~,View) void 
}

class CreateEventActivity { 
+ String TAG$
~ ActivityCreateEventBinding binding
~ CreateEventModel model
~ EventRepository eventRepository
- EventGeneralFragment eventGeneralFragment
- EventDateTimeFragment eventDateTimeFragment
- EventDeadlinesFragment eventDeadlinesFragment
- EventLotteryFragment eventLotteryFragment
- EventStyleFragment eventStyleFragment
- Fragment fragment
# onCreate(Bundle) void 
- navigateToSection(Section) void 
+ openCalendarBottomSheet(MutableLiveData~Optional~Date~~,View) void 
+ openTimeBottomSheet(MutableLiveData~Optional~Time~~,View) void 
+ onDestroy() void 
}

class EventLotteryFragment { 
- String TAG$
- ViewInputEventLotteryBinding binding
- CreateEventModel model
- BottomSheetProvider bottomSheetProvider
+ onCreateView(LayoutInflater,ViewGroup,Bundle) View 
+ onViewCreated(View,Bundle) void 
- setupInputListeners() void 
+ valid(InputFragment) boolean 
+ extract(Event.Builder) Event.Builder 
+ onDestroyView() void 
}

class EventDateTimeFragment { 
- String TAG$
- ViewInputEventDatetimeBinding binding
- CreateEventModel model
- BottomSheetProvider bottomSheetProvider
+ onCreateView(LayoutInflater,ViewGroup,Bundle) View 
+ onViewCreated(View,Bundle) void 
- setupDateTimePickers() void 
+ valid(InputFragment) boolean 
+ extract(Event.Builder) Event.Builder 
+ onDestroyView() void 
}

class Time { 
- int hour
- int minute
+ Time(int,int) Time 
+ Time() Time 
+ getHour() int 
+ setHour(int) void 
+ getMinute() int 
+ setMinute(int) void 
+ toString() String 
+ compareTo(Time) int 
+ lessThan(Time) boolean 
}

class EventGeneralFragment { 
- ViewInputEventGeneralBinding binding
- CreateEventModel model
~ categories List~Integer~ 
+ onCreateView(LayoutInflater,ViewGroup,Bundle) View 
+ onViewCreated(View,Bundle) void 
+ valid(InputFragment) boolean 
+ extract(Event.Builder) Event.Builder 
+ onDestroyView() void 
}

class CreateEventModel { 
- SimpleDateFormat dateFormatter
- MutableLiveData~Section~ section
+ MutableLiveData~String~ title
+ MutableLiveData~String~ description
+ MutableLiveData~String~ tagline
+ MutableLiveData~Boolean~ singleDayEvent
+ MutableLiveData~Optional~Date~~ eventDate
+ MutableLiveData~Optional~Time~~ eventStartTime
+ MutableLiveData~Optional~Time~~ eventEndTime
+ MutableLiveData~Optional~Date~~ registrationStartDate
+ MutableLiveData~Optional~Date~~ registrationEndDate
+ MutableLiveData~Optional~Date~~ initialSelectionStartDate
+ MutableLiveData~Optional~Date~~ initialSelectionEndDate
+ MutableLiveData~Optional~Date~~ finalAttendeeSelectionDate
+ MutableLiveData~Boolean~ hasWaitlistCapacity
+ MutableLiveData~Boolean~ hasLocationRequirement
+ MutableLiveData~Optional~Integer~~ waitlistCapacity
+ MutableLiveData~Optional~Integer~~ eventCapacity
+ MutableLiveData~Optional~Date~~ lotteryDate
+ MutableLiveData~Optional~Time~~ lotteryTime
+ MutableLiveData~Optional~Uri~~ image
+ MutableLiveData~Optional~Color~~ color
+ CreateEventModel() CreateEventModel 
+ dateDisplay(MutableLiveData~Optional~Date~~) LiveData~String~ 
+ eventDateDisplay() LiveData~String~ 
+ eventStartTimeDisplay() LiveData~String~ 
+ eventEndTimeDisplay() LiveData~String~ 
+ registrationStartDateDisplay() LiveData~String~ 
+ registrationEndDateDisplay() LiveData~String~ 
+ initialSelectionStartDateDisplay() LiveData~String~ 
+ initialSelectionEndDateDisplay() LiveData~String~ 
+ finalAttendeeSelectionDateDisplay() LiveData~String~ 
+ waitlistCapacityDisplay() LiveData~String~ 
+ eventCapacityDisplay() LiveData~String~ 
+ lotteryDateDisplay() LiveData~String~ 
+ lotteryTimeDisplay() LiveData~String~ 
+ getSection() LiveData~Section~ 
+ getLeftButtonVisibility() LiveData~Integer~ 
+ getRightButtonVisibility() LiveData~Integer~ 
+ getRightButtonText() String 
+ nextSection(InputFragment) void 
+ prevSection() void 
}

class InputFragment { 
<<interface>>
~ valid(InputFragment) boolean 
~ extract(Event.Builder) Event.Builder 
}

class EventStyleFragment { 
- String TAG$
- ViewInputEventStyleBinding binding
- CreateEventModel model
- ActivityResultLauncher~PickVisualMediaRequest~ pickMedia
+ onCreate(Bundle) void 
+ onCreateView(LayoutInflater,ViewGroup,Bundle) View 
+ onViewCreated(View,Bundle) void 
- setupStylePickers() void 
+ valid(InputFragment) boolean 
+ extract(Event.Builder) Event.Builder 
+ onDestroyView() void 
}

class DraftEventsFragment { 
~ FragmentDraftEventsBinding binding
+ onCreateView(LayoutInflater,ViewGroup,Bundle) View 
+ onViewCreated(View,Bundle) void 
+ onDestroy() void 
}

DraftEventsFragment --> CreateEventActivity : starts

CreateEventActivity "1" o-- "1" EventGeneralFragment : hosts
CreateEventActivity "1" o-- "1" EventDateTimeFragment : hosts
CreateEventActivity "1" o-- "1" EventDeadlinesFragment : hosts
CreateEventActivity "1" o-- "1" EventLotteryFragment : hosts
CreateEventActivity "1" o-- "1" EventStyleFragment : hosts

CreateEventActivity "1" o-- "1" CreateEventModel : watches

%% Event builder relationship
Event_Builder -- EventGeneralFragment : fills
Event_Builder -- EventDateTimeFragment : fills
Event_Builder -- EventDeadlinesFragment : fills
Event_Builder -- EventLotteryFragment : fills
Event_Builder -- EventStyleFragment : fills

%% Create Event Model Relationship
CreateEventModel "1" -- "1" EventGeneralFragment : stores input data
CreateEventModel "1" -- "1" EventDateTimeFragment : stores input data
CreateEventModel "1" -- "1" EventDeadlinesFragment : stores input data
CreateEventModel "1" -- "1" EventLotteryFragment : stores input data
CreateEventModel "1" -- "1" EventStyleFragment : stores input data

CreateEventModel "1" *-- "1" Section : stores
CreateEventModel "1" --> "1" Section : changes

%% implements
BottomSheetProvider <|.. CreateEventActivity
 
InputFragment <|.. EventGeneralFragment
InputFragment <|.. EventDateTimeFragment
InputFragment <|.. EventDeadlinesFragment
InputFragment <|.. EventLotteryFragment
InputFragment <|.. EventStyleFragment


