---
title: events package
config:
  layout: elk
  theme: light
  elk:
    nodePlacementStrategy: SIMPLE
  htmlLabels: false
---

classDiagram
class EventRepository 

class EventRepository_WaitlistSizeListener 

class EventRepository_WaitlistEntrantsCallback 

class EventRepository_UserLocationCallback 

class EventRepository_WaitlistLocationsCallback 

class EventRepository_InvitedEntrantsCallback 

class EventRepository_UserLocationFromInvitedCallback 

class EventRepository_InvitedLocationsCallback 

class EventRepository_CancelledEntrantsCallback 

class EventRepository_UserLocationFromCancelledCallback 

class EventRepository_CancelledLocationsCallback 

class EventRepository_SelectedEntrantsCallback 

class EventRepository_UserLocationFromSelectedCallback 

class EventRepository_SelectedLocationsCallback 

class OrganizerEntrantsFragment 

class EventViewFragment 

class Event 

class Event_Builder 

class EventListFragment 

class EventAdapter 

class EventAdapter_MyViewHolder 

class EventAdapter_OnEventListener 

Event "0..*" --o "1" EventRepository : manages

%% Nesting Relationships
EventRepository_WaitlistSizeListener <.. EventRepository : << contains >>
EventRepository_WaitlistEntrantsCallback <.. EventRepository : << contains >>
EventRepository_UserLocationCallback <.. EventRepository : << contains >>
EventRepository_WaitlistLocationsCallback <.. EventRepository : << contains >>
EventRepository_InvitedEntrantsCallback <.. EventRepository : << contains >>
EventRepository_UserLocationFromInvitedCallback <.. EventRepository : << contains >>
EventRepository_InvitedLocationsCallback <.. EventRepository : << contains >>
EventRepository_CancelledEntrantsCallback <.. EventRepository : << contains >>
EventRepository_UserLocationFromCancelledCallback <.. EventRepository : << contains >>
EventRepository_CancelledLocationsCallback <.. EventRepository : << contains >>
EventRepository_SelectedEntrantsCallback <.. EventRepository : << contains >>
EventRepository_UserLocationFromSelectedCallback <.. EventRepository : << contains >>
EventRepository_SelectedLocationsCallback <.. EventRepository : << contains >>

Event_Builder <.. Event : << contains >>
EventAdapter_OnEventListener <.. EventAdapter : << contains >>

%% OrganizerEntrantsFragment relationships.
%% shows all entrants for the event
%% shows entrant map locations
%% sends notifications to all entrants on waitlist (to different groups)
%% export final attendees as CSV
%% cancel entrants
%% draw replacements
Event "1" --o "1" OrganizerEntrantsFragment : organizer management of
EventRepository "1" --o "1" OrganizerEntrantsFragment
NotificationRepository "1" --o "1" OrganizerEntrantsFragment
ProfileRepository "1" --o "1" OrganizerEntrantsFragment


Event "1" --o "1" EventViewFragment : shows details for
EventRepository "1" --o "1" EventViewFragment

Event "1" <-- "1" Event_Builder : assembles

Event "0..*" --o "1" EventListFragment : shows
