---
title: login package
config:
  htmlLabels: false
---

classDiagram
class LoginStartScanningFragment { 
- Button button_continue
- String TAG$
- String username
- String email
- String phoneNumber
- String deviceId
- String uid
- ProfileViewModel profileViewModel
- FirebaseAuth mAuth
- boolean isObserverInitialized
+ onCreateView(LayoutInflater,ViewGroup,Bundle) View 
- setupUI(View) void 
+ onResume() void 
- updateOrCreateUser() void 
- saveProfile(String) void 
}

class LoginViewFragment { 
~ FirebaseAuth mAuth
- Button button_start_scanning
- Button button_criteria
+ onCreateView(LayoutInflater,ViewGroup,Bundle) View 
+ onViewCreated(View,Bundle) void 
}

class LoginViewModel { 
- String TAG$
- FirebaseAuth mAuth
- MutableLiveData~FirebaseUser~ userLiveData
- MutableLiveData~Boolean~ isNewUserLiveData
- ProfileViewModel profileViewModel
+ LoginViewModel(Application) LoginViewModel 
+ getUserLiveData() LiveData~FirebaseUser~ 
+ getIsNewUserLiveData() LiveData~Boolean~ 
+ checkOrSignIn() void 
- signInAnonymously() void 
- handleUserProfile(FirebaseUser) void 
}

class LoginCriteriaFragment { 
- ImageButton button_back
+ onCreateView(LayoutInflater,ViewGroup,Bundle) View 
}



