---
title: login package
config:
  htmlLabels: false
---

classDiagram
    direction TB

    class MainActivity 

    class LoginViewFragment 

    class LoginCriteriaFragment 

    class LoginStartScanningFragment 

    class ProfileViewModel 

    class ProfileModel 

    %% Relationships

    LoginStartScanningFragment --> ProfileViewModel
    ProfileViewModel --> ProfileModel

    LoginCriteriaFragment --> MainActivity
    LoginViewFragment --> MainActivity
    LoginStartScanningFragment --> MainActivity

    LoginViewFragment --> LoginCriteriaFragment : "navigates to"
    LoginViewFragment --> LoginStartScanningFragment : "navigates to"
    LoginStartScanningFragment --> EventListFragment : "navigates to"


