%% Syntax here can be weird. Go reference:
%% https://mermaid.js.org/syntax/classDiagram.html
classDiagram
    note "This is a note"
    class InitActivity{

    }

    class MainActivity {

    }
    class EventViewFragment {

    }
    class CreateEventFragment {

    }
    class ProfileViewFragment {

    }

    class EventActivity {

    }



