%% Syntax here can be weird. Go reference:
%% https://mermaid.js.org/syntax/classDiagram.html
classDiagram
    note "This is a note"
    class InitActivity{
        - binding: InitActivityBinding
    }

    class MainActivity {
        - binding: MainActivityBinding
    }
    class EventViewFragment {
        - binding: EventViewFragmentBinding
    }
    class CreateEventFragment {
        - binding: CreateEventFragmentBinding
    }
    class ProfileViewFragment {
        - binding: ProfileViewFragmentBinding
    }

    class EventActivity {
        - binding: EventActivityBinding
    }
