---
title: notifications package
config:
  htmlLabels: false
---

classDiagram
class NotificationAdapter 


class MyFirebaseMessagingService 

class Notification 

class NotificationFragment 

class NotificationRepository 

Notification -- NotificationAdapter
Notification -- NotificationFragment
NotificationRepository -- NotificationAdapter
NotificationAdapter -- NotificationFragment
NotificationRepository -- NotificationFragment

