---
title: profile package
config:
  htmlLabels: false
---
classDiagram

class ProfileViewModel 

class ProfileModel 

class ProfileFragment 

class ProfileRepository 

class ProfileRepository_ReadCallback 

class ProfileRepository_WriteCallback 

class AccountSettingsFragment 

class InputValidator 

ProfileViewModel "1" --> "1" ProfileRepository : uses

ProfileViewModel "1" *-- "0..1" ProfileModel : observes/manages as live data

ProfileFragment "1" *-- "1" ProfileViewModel : observes

ProfileFragment "1" *-- "0..1" ProfileModel : displays

ProfileRepository "1" ..> "*" ProfileModel : creates/manages

ProfileRepository "1" *-- "2" ProfileRepository_ReadCallback : defines

ProfileRepository "1" *-- "2" ProfileRepository_WriteCallback : defines

ProfileRepository_ReadCallback "1" ..> "1" ProfileModel : returns

AccountSettingsFragment "1" *-- "1" ProfileViewModel : uses

AccountSettingsFragment "1" ..> "1" InputValidator : validates with

ProfileFragment "1" ..> "1" InputValidator : validates with
