name: Mirror CRC cards to the Wiki

# We run anytime changes to the crc folder are pushed to main
on:
  push: 
    branch: 
      - main
    paths:
      - 'doc/crc/**/*.yml'


# https://github.com/orgs/community/discussions/56893#discussioncomment-6054377
# Turns out
permissions:
  contents: write

jobs:
  install-crcgen:
    runs-on: ubuntu-latest
    steps:
      - name: Download crcgen Binary 
        shell: bash
        run: |
          echo "Started crcgen Install"
          wget -q -O /usr/local/bin/crcgen "https://github.com/GenericConfluent/crcgen/releases/download/v0.1.0/crcgen"
          chmod +x /usr/local/bin/crcgen
          echo "Finished crcgen Install"

      # Clone the source of our repository so we can get into doc/crc.
      # Here we are only fetching the most recent commit and even then 
      # only grabbing docs. So should be pretty quick.
      - uses: actions/checkout@v5
        with:
          sparse-checkout: doc

      # As soon as we have the binary and docs we can generate the 
      # rendered cards. Outputs: $GITHUB_WORKSPACE/CRC.md
      - name: Build Cardpage from `doc/crc`
        shell: bash
        run: |
          # I need this to get the recursive glob to grab stuff
          # in the current dir.
          shopt -s globstar
          /usr/local/bin/crcgen -o CRC.md rocket-radar/doc/crc/**/*.yml

      # Clone the wiki into the $GITHUB_WORKSPACE/wiki (where $GITHUB_WORKSPACE is
      # the default working directory for scripts.
      - uses: actions/checkout@v5
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki

      - name: Update the wiki page
        shell: bash
        run: |
          mv CRC.md wiki/

      # Deal with configuring dummy git user and email.
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: mirror crc cards"
          repository: wiki
